# on:
#   schedule:
#     - cron: "0 22 * * *"
on:
  push:
    branches: main

jobs:
  setup_daily_jobs:
    name: Setup Daily Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Script
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          DAILY_TASK_DATABASE_ID: ${{ secrets.DAILY_TASK_DATABASE_ID }}
        run: |
          go run setup_daily_jobs.go

